name: Deploy to Azure (Auto)

on:
  push:
    branches: [ main ]
    paths:
      - 'infrastructure/**'
      - 'azure-data-pipeline/**'
      - '.github/workflows/azure-deploy.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - prod

env:
  PROJECT_NAME: mass-smart-space
  LOCATION: japaneast
  RESOURCE_GROUP: MS-Lab-Proj-RG

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az version

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set deployment environment
      id: set-env
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
        else
          echo "ENVIRONMENT=dev" >> $GITHUB_ENV
        fi

    - name: Verify Resource Group exists
      run: |
        echo "Checking if resource group ${{ env.RESOURCE_GROUP }} exists..."
        if ! az group show --name ${{ env.RESOURCE_GROUP }} --query name --output tsv; then
          echo "Creating resource group ${{ env.RESOURCE_GROUP }}..."
          az group create \
            --name ${{ env.RESOURCE_GROUP }} \
            --location ${{ env.LOCATION }}
        else
          echo "Resource group ${{ env.RESOURCE_GROUP }} already exists."
        fi

    - name: Check parameters file
      id: check-params
      run: |
        cd infrastructure
        if [ -f "parameters.${{ env.ENVIRONMENT }}.json" ]; then
          echo "PARAMS_FILE=parameters.${{ env.ENVIRONMENT }}.json" >> $GITHUB_ENV
          echo "Using parameters file: parameters.${{ env.ENVIRONMENT }}.json"
        else
          echo "PARAMS_FILE=" >> $GITHUB_ENV
          echo "No parameters file found, using default values"
        fi

    - name: Deploy Infrastructure
      run: |
        cd infrastructure
        if [ -n "${{ env.PARAMS_FILE }}" ]; then
          echo "Deploying with parameters file: ${{ env.PARAMS_FILE }}"
          az deployment group create \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --template-file main.bicep \
            --parameters ${{ env.PARAMS_FILE }} \
            --name "auto-deployment-$(date +%Y%m%d-%H%M%S)"
        else
          echo "Deploying with default parameters"
          az deployment group create \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --template-file main.bicep \
            --name "auto-deployment-$(date +%Y%m%d-%H%M%S)"
        fi

    - name: Deploy API
      run: |
        cd azure-data-pipeline/api/dashboard-api
        zip -r api.zip .
        az webapp deployment source config-zip \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --name "api-${{ env.PROJECT_NAME }}-${{ env.ENVIRONMENT }}" \
          --src api.zip

    - name: Deployment summary
      run: |
        echo "=== Auto Deployment Summary ==="
        echo "Resource Group: ${{ env.RESOURCE_GROUP }}"
        echo "Environment: ${{ env.ENVIRONMENT }}"
        echo "Location: ${{ env.LOCATION }}"
        echo "Trigger: ${{ github.event_name }}"
        echo "Parameters File: ${{ env.PARAMS_FILE }}"
