name: Deploy to Azure (Auto)

on:
  push:
    branches: [ main ]
    paths:
      - 'infrastructure/**'
      - 'azure-data-pipeline/**'
      - '.github/workflows/azure-deploy.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - prod

env:
  PROJECT_NAME: mass-smart-space
  LOCATION: japaneast

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | bash
        az version

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set deployment environment
      id: set-env
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
        else
          echo "ENVIRONMENT=dev" >> $GITHUB_ENV
        fi
        echo "RESOURCE_GROUP=rg-${{ env.PROJECT_NAME }}-${{ env.ENVIRONMENT }}" >> $GITHUB_ENV

    - name: Create Resource Group
      run: |
        az group create \
          --name ${{ env.RESOURCE_GROUP }} \
          --location ${{ env.LOCATION }}

    - name: Deploy Infrastructure
      run: |
        cd infrastructure
        az deployment group create \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --template-file main.bicep \
          --parameters parameters.${{ env.ENVIRONMENT }}.json \
          --name "auto-deployment-$(date +%Y%m%d-%H%M%S)"

    - name: Deploy API
      run: |
        cd azure-data-pipeline/api/dashboard-api
        zip -r api.zip .
        az webapp deployment source config-zip \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --name "api-${{ env.PROJECT_NAME }}-${{ env.ENVIRONMENT }}" \
          --src api.zip

    - name: Deployment summary
      run: |
        echo "=== Auto Deployment Summary ==="
        echo "Resource Group: ${{ env.RESOURCE_GROUP }}"
        echo "Environment: ${{ env.ENVIRONMENT }}"
        echo "Location: ${{ env.LOCATION }}"
        echo "Trigger: ${{ github.event_name }}"
